name: Meeting
description: Create a new ticket for a new feature request
title: "[Meeting]: "
labels: ["meeting"]
projects:  ["spe-uob/2023-WildlifeWest"]

body:
  - type: input
    id: meeting_date
    attributes:
      label: "Meeting Date"
      description: Date of meeting
      placeholder: "day/month/year"
    validations:
      required: true
  - type: input
    id: meeting_length
    attributes:
      label: "Meeting Length"
      description: Length of meeting
      placeholder: "day/month/year"
    validations:
      required: true
  - type: input
    id: attendees
    attributes:
      label: "Attendees"
      description: Who are we meeting?
      placeholder: Andreea
    validations:
      required: true
